apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery
  labels:
    app: delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
        - name: delivery
          image: 004814395703.dkr.ecr.us-east-1.amazonaws.com/delivery:latest
          ports:
            - containerPort: 8080
