apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    app: product
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: 004814395703.dkr.ecr.us-east-1.amazonaws.com/product:latest
          ports:
            - containerPort: 8080
